import { describe, expect, test } from "bun:test";
import { parseLockfile } from "../../src/core/lockfile.js";

describe("lockfile corruption handling", () => {
	test("throws on empty content", () => {
		expect(() => parseLockfile("")).toThrow("Corrupted lockfile");
	});

	test("throws on non-object YAML", () => {
		expect(() => parseLockfile("just a string")).toThrow("Corrupted lockfile");
	});

	test("throws on YAML array instead of mapping", () => {
		// YAML arrays don't have `lockfile_version` either — they hit the
		// missing-key branch and surface the named-field error (#123).
		expect(() => parseLockfile("- item1\n- item2\n")).toThrow(/lockfile_version/);
	});

	test("throws on wrong lockfile_version", () => {
		expect(() => parseLockfile("lockfile_version: 99\npackages: {}\n")).toThrow(
			"Unsupported lockfile version",
		);
	});

	test("throws on missing lockfile_version", () => {
		// Naming the missing field, not the undefined value (#123).
		expect(() => parseLockfile("packages: {}\n")).toThrow(/lockfile_version/);
	});

	test("handles lockfile with only comments", () => {
		const content = "# skilltree.lock\n# Generated by skilltree\n";
		expect(() => parseLockfile(content)).toThrow("Corrupted lockfile");
	});

	test("handles truncated YAML (partial write)", () => {
		const truncated = "lockfile_version: 1\npackages:\n  my-skill:\n    type: sk";
		// Should parse but with incomplete data — or throw
		// The YAML parser may still parse partial content
		const result = parseLockfile(truncated);
		// Truncated value may be accepted by YAML parser as a string
		expect(result.lockfile_version).toBe(1);
	});

	test("parses valid lockfile with extra fields gracefully", () => {
		const content =
			"lockfile_version: 1\npackages:\n  my-skill:\n    type: skill\n    group: prod\n    path: ./skills/my-skill\n    commit: HEAD\n    dependencies: []\n    extra_field: ignored\n";
		const result = parseLockfile(content);
		expect(result.packages["my-skill"]?.type).toBe("skill");
	});

	test("parses lockfile with empty packages", () => {
		const content = "lockfile_version: 1\npackages: {}\n";
		const result = parseLockfile(content);
		expect(Object.keys(result.packages)).toHaveLength(0);
	});
});
