import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import semver from "semver";
import YAML from "yaml";
import pkg from "../../package.json";
import type { Dependency, Lockfile, LockfileEntry, Manifest } from "../types.js";
import { isLocalDependency, isRemoteDependency } from "../types.js";
import { resolveGlobalLockfilePath, resolveLockfilePath } from "./filenames.js";
import type { ResolvedEntity } from "./graph.js";
import { expandSources } from "./manifest.js";
import { collapseTilde, expandTilde } from "./paths.js";

/**
 * Build a lockfile from resolved entities.
 * When `global: true`, collapses absolute paths to tilde format for portability.
 */
export function buildLockfile(
	entities: Map<string, ResolvedEntity>,
	options?: { global?: boolean },
): Lockfile {
	const packages: Record<string, LockfileEntry> = {};
	const isGlobal = options?.global ?? false;

	// Use install order for consistent output, but sort keys alphabetically
	const sortedKeys = [...entities.keys()].sort();

	for (const compositeKey of sortedKeys) {
		const entity = entities.get(compositeKey);
		if (!entity) continue;

		const entryPath = isGlobal && entity.local ? collapseTilde(entity.path) : entity.path;

		const entry: LockfileEntry = {
			type: entity.type,
			group: entity.group,
			path: entryPath,
			commit: entity.commit,
			dependencies: [...entity.dependencies].sort(),
		};

		if (entity.repo) {
			entry.repo = entity.repo;
		}

		if (entity.local) {
			entry.source = "local";
		}

		if (entity.version) {
			entry.version = entity.version;
		}

		if (entity.name !== entity.key) {
			entry.name = entity.name;
		}

		packages[entity.key] = entry;
	}

	return {
		lockfile_version: 1,
		packages,
	};
}

/**
 * Serialize a lockfile to YAML string.
 */
export function serializeLockfile(lockfile: Lockfile): string {
	const header = `# skilltree.lock -- DO NOT EDIT MANUALLY\n# Generated by skilltree v${pkg.version}\n`;
	return header + YAML.stringify(lockfile, { lineWidth: 0 });
}

/**
 * Parse a lockfile from YAML string.
 */
export function parseLockfile(content: string): Lockfile {
	// Strip header comments
	const yamlContent = content
		.split("\n")
		.filter((line) => !line.startsWith("#"))
		.join("\n");
	const raw = YAML.parse(yamlContent) as Lockfile | null;

	if (!raw || typeof raw !== "object") {
		throw new Error("Corrupted lockfile: could not parse YAML");
	}

	if (raw.lockfile_version !== 1) {
		throw new Error(`Unsupported lockfile version: ${raw.lockfile_version}`);
	}

	assertAcyclic(raw);
	return raw;
}

/**
 * The resolver rejects cycles via topological sort before writing a lockfile,
 * so any cycle in `packages` indicates corruption (hand-edit, future
 * skilltree version with a serialization bug, etc.). Validate once on read so
 * downstream consumers (deps tree, install --frozen) can trust acyclicity
 * without re-checking.
 */
function assertAcyclic(lockfile: Lockfile): void {
	const WHITE = 0;
	const GREY = 1;
	const BLACK = 2;
	const color = new Map<string, number>();
	for (const name of Object.keys(lockfile.packages)) color.set(name, WHITE);

	// Iterative DFS to keep stack depth bounded on deep graphs.
	for (const start of color.keys()) {
		if (color.get(start) !== WHITE) continue;
		// Each frame: [name, indexOfNextChildToVisit]
		const stack: Array<[string, number]> = [[start, 0]];
		color.set(start, GREY);
		while (stack.length > 0) {
			const top = stack[stack.length - 1];
			if (!top) break;
			const [name, idx] = top;
			const deps = lockfile.packages[name]?.dependencies ?? [];
			if (idx >= deps.length) {
				color.set(name, BLACK);
				stack.pop();
				continue;
			}
			top[1] = idx + 1;
			const child = deps[idx];
			if (!child || !lockfile.packages[child]) continue;
			const c = color.get(child);
			if (c === GREY) {
				const cycle = [
					...stack.map(([n]) => n).slice(stack.findIndex(([n]) => n === child)),
					child,
				];
				throw new Error(
					`Lockfile is corrupt: dependency cycle detected: ${cycle.join(" → ")}. The resolver rejects cycles, so this lockfile was hand-edited or written by an incompatible tool. Run 'skilltree install' to regenerate.`,
				);
			}
			if (c === WHITE) {
				color.set(child, GREY);
				stack.push([child, 0]);
			}
		}
	}
}

/**
 * Read a lockfile from disk. Returns `null` only when the file is absent.
 * Parse errors (corruption, unsupported version, dependency cycle) propagate
 * so callers don't silently fall through to "no lockfile" remediation.
 */
export async function readLockfile(dir: string): Promise<Lockfile | null> {
	const { path } = resolveLockfilePath(dir);
	let content: string;
	try {
		content = await readFile(path, "utf-8");
	} catch (err: unknown) {
		if (err instanceof Error && "code" in err && err.code === "ENOENT") return null;
		throw err;
	}
	return parseLockfile(content);
}

/**
 * Write a lockfile to disk.
 */
export async function writeLockfile(dir: string, lockfile: Lockfile): Promise<void> {
	const { path } = resolveLockfilePath(dir);
	await writeFile(path, serializeLockfile(lockfile), "utf-8");
}

// --- Global lockfile ---

export async function readGlobalLockfile(globalDir?: string): Promise<Lockfile | null> {
	const { path } = resolveGlobalLockfilePath(globalDir);
	let content: string;
	try {
		content = await readFile(path, "utf-8");
	} catch (err: unknown) {
		if (err instanceof Error && "code" in err && err.code === "ENOENT") return null;
		throw err;
	}
	return parseLockfile(content);
}

export async function writeGlobalLockfile(lockfile: Lockfile, globalDir?: string): Promise<void> {
	const { path } = resolveGlobalLockfilePath(globalDir);
	await mkdir(dirname(path), { recursive: true });
	await writeFile(path, serializeLockfile(lockfile), "utf-8");
}

export interface LockfileDiff {
	unchanged: string[]; // keys present in both, compatible
	added: string[]; // in manifest but not lockfile
	changed: string[]; // in both but repo/version changed
	removed: string[]; // in lockfile but not manifest
}

/**
 * Diff a manifest against an existing lockfile.
 * Returns which entries are unchanged, added, changed, or removed.
 */
export function diffManifestLockfile(manifest: Manifest, lockfile: Lockfile): LockfileDiff {
	const expanded = expandSources(manifest);
	const allManifestDeps: Record<string, Dependency> = {
		...expanded.dependencies,
		...expanded["dev-dependencies"],
	};

	const manifestKeys = new Set(Object.keys(allManifestDeps));
	const lockfileKeys = new Set(Object.keys(lockfile.packages));

	const unchanged: string[] = [];
	const added: string[] = [];
	const changed: string[] = [];
	const removed: string[] = [];

	for (const key of manifestKeys) {
		const dep = allManifestDeps[key];
		const locked = lockfile.packages[key];

		if (!locked || !dep) {
			added.push(key);
		} else {
			classifyDep(dep, locked, key, unchanged, changed);
		}
	}

	// Check for removed entries (in lockfile but not manifest)
	// Only check direct deps, not transitive
	for (const key of lockfileKeys) {
		if (!manifestKeys.has(key)) {
			// Could be a transitive dep — check if it's reachable from any manifest key
			const isTransitive = isReachableFromManifest(key, lockfile, manifestKeys);
			if (!isTransitive) {
				removed.push(key);
			}
		}
	}

	return { unchanged, added, changed, removed };
}

/**
 * Build ResolvedEntity map + resolution context from a lockfile.
 * Shared between frozenInstall and resolveFromLockfile to avoid duplication.
 */
export function entitiesFromLockfile(lockfile: Lockfile): {
	entities: Map<string, ResolvedEntity>;
	resolutionContext: Map<string, string>;
} {
	const entities = new Map<string, ResolvedEntity>();
	const resolutionContext = new Map<string, string>();

	for (const [key, entry] of Object.entries(lockfile.packages)) {
		const compositeKey = `${entry.type}:${entry.name ?? key}`;
		const isLocal = entry.source === "local";
		const entryPath = expandTilde(entry.path);

		entities.set(compositeKey, {
			key,
			name: entry.name ?? key,
			type: entry.type,
			group: entry.group,
			repo: entry.repo,
			path: entryPath,
			version: entry.version,
			commit: entry.commit,
			local: isLocal,
			dependencies: entry.dependencies,
		});
		resolutionContext.set(entry.name ?? key, compositeKey);
	}

	return { entities, resolutionContext };
}

function classifyDep(
	dep: Dependency,
	locked: LockfileEntry,
	key: string,
	unchanged: string[],
	changed: string[],
): void {
	if (isLocalDependency(dep)) {
		unchanged.push(key);
		return;
	}
	if (isRemoteDependency(dep)) {
		if (dep.repo !== locked.repo) {
			changed.push(key);
			return;
		}
		const constraint = dep.version ?? "*";
		if (locked.version && constraint !== "*" && !semver.satisfies(locked.version, constraint)) {
			changed.push(key);
			return;
		}
	}
	unchanged.push(key);
}

function isReachableFromManifest(
	target: string,
	lockfile: Lockfile,
	manifestKeys: Set<string>,
): boolean {
	const visited = new Set<string>();

	function walk(key: string): boolean {
		if (visited.has(key)) return false;
		visited.add(key);
		if (key === target) return true;
		const entry = lockfile.packages[key];
		if (!entry) return false;
		return entry.dependencies.some((dep) => walk(dep));
	}

	for (const mk of manifestKeys) {
		if (walk(mk)) return true;
	}
	return false;
}
